version: "3.7"

services:
  myexams-site:
    postdesign: postdesign
    image: postdesign:0.1.0
    restart: always
    volumes:
      - ./storage:/app/storage
    ports:
      - ${APP_PORT}:80
    environment:
      ## App Configuration
      - APP_PORT=80
      ## Time Zone
      - TZ=${TZ}
      ## Telegram API
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_ALLOW_USERS=${TELEGRAM_ALLOW_USERS}