version: "3.7"

services:
  myexams-site:
    container_name: myexams-site
    image: myexams-site:0.1.0-dev-1
    restart: always
    volumes:
      - ./myexams-site-storage:/app/storage
    ports:
      - ${APP_PORT}:80
    environment:
      ## App Configuration
      - APP_PORT=80
      ## Time Zone
      - TZ=${TZ}
      ## Private Key
      - ACCESS_KEY_HASH=${ACCESS_KEY_HASH}
      ## Telegram API
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_ALLOW_USERS=${TELEGRAM_ALLOW_USERS}